### PR TITLE
Various Fixes

### PR DESCRIPTION
**Pull request by Orbitally**
Made a whole bunch of grammar fixes as well as converted all of the images to `.jpg`'s in an attempt to speed up the website.

### CODE REVIEW

**Review by Orbitally — COMMENTED** [review]
fix: fixed various grammar issues in Darwin's bio

Not sure why the commit didn't get named properly

**Comment by Orbitally** [comment]
Should also give a big thanks to @Mr Republic (Discord) for helping proofread the site

**Comment by Orbitally** [comment]
https://github.com/RegDesigns-Official/RegDesigns-Website/pull/26/commits/08cc34d40709d7a60627b73b7fdcdeb47dad1004 Figured it made sense to remove it for the time being so that nobody got confused trying to use that link to buy it from SimMarket just until it was actually posted.

**Comment by Orbitally** [comment]
Should also give a big thanks to [Mr Republic](https://discord.com/users/618737261797703681) (Discord) for helping proofread the site

**Comment by Orbitally** [comment]
@Awemeter the PR should be all set to be merged

**Comment by Awemeter** [comment]
Can u also compress the new images I added for 360

**Pull request merged**
